version: '2'
services:
  es:
    build: .
    image: predictor-word:latest
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS="-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"